Repository cea-hpc/clustershell, pull requests merged in 2024-09, with the labels that each got.

#558 Additional Slurm example bindings
  conf/groups.conf.d/slurm.conf.example
Labels: Doc, Config

#561 Additional Slurm binding for mapping nodes to reservations
  conf/groups.conf.d/slurm.conf.example
Labels: Config

#556 Fix tests for libexpat >=2.6.0 (or with CVE-2023-52425 fixes backported)
  tests/TreeGatewayTest.py
Labels: Quality

#569 Communication: sax parser: add flush() after feed() (#556)
  lib/ClusterShell/Communication.py
Labels: Lib/Tree

#570 CLI/Nodeset: omit @source: prefix for cluset -s source -L (#563)
  lib/ClusterShell/CLI/Nodeset.py
  tests/CLINodesetTest.py
Labels: Scripts
